### ISSUE TITLE
Error while searching.

### ISSUE THREAD

**Issue by yORmOmi** [insomniachi/Totoro#34]
**Describe the bug**
When I try to search for something on the search tab and press entered an error will show.

**To Reproduce**
1. Go to 'Discover > search'
2. Click on 'search input, and type something in it.'
3. Press enter button.
4. See the error.

**Expected behavior**
```
System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at Totoro.Plugins.Anime.AllAnime.Catalog.Search(String query)+MoveNext()
   at Totoro.Plugins.Anime.AllAnime.Catalog.Search(String query)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
```
**Screenshots**
![image](https://github.com/insomniachi/Totoro/assets/133837794/6d243675-45b5-4634-bc8f-20f080ef3d3d)
config
![image](https://github.com/insomniachi/Totoro/assets/133837794/8acc3a1d-fda0-422c-8107-9ff1bccbfb24)

**Comment by yORmOmi** [comment]
I found a simple fix using "Marin"
I also tested it on other stream providers and it did not work including zoro[execept Marin]

**Comment by insomniachi** [comment]
This was specific to the term you searched "one pi"
all anime returns some movies, which doesn't have season or mal id / anilist id

you'll get fix for crash without updating the app.
however anime without anilist/mal id is not addressed, that will need an application update when fixed.

**Comment by yORmOmi** [comment]
> This was specific to the term you searched "one pi" all anime returns some movies, which doesn't have season or mal id / anilist id
> 
> you'll get fix for crash without updating the app. however anime without anilist/mal id is not addressed, that will need an application update when fixed.

👍 Thanks, also your application is amazing!
