### ISSUE TITLE
all 6 English Anime Plugins broken.

### ISSUE THREAD

**Issue by bachig26** [insomniachi/Totoro#76]
**Describe the bug**

1. AllAnime
2. AnimePahe (doesn't wok for over an year or so, as there's ip block in germany for this site)
3. Aniwave
4. GogoAnime
5. Yugen Anime - it doesn't play any episodes, just opens the player and just stays idle.
6. Marin

**Desktop (please complete the following information):**
 - Version: 1.4.6

**Additional Info**

1. Marin:
```
Flurl.Http.FlurlHttpException: Call failed with status code 504 (Gateway Timeout): GET https://marin.moe/
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Totoro.Plugins.Anime.Marin.AiredEpisodesProvider.GetRecentlyAiredEpisodes(Int32 page)+MoveNext()
   at Totoro.Plugins.Anime.Marin.AiredEpisodesProvider.GetRecentlyAiredEpisodes(Int32 page)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
```

2. AllAnime:

![y4bvtr1doV](https://github.com/insomniachi/Totoro/assets/96393348/9ea09adf-22f0-4997-8e7b-76304b53e499)

3. AnimePahe
```
Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): GET https://animepahe.ru/api?m=airing&page=1
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveString(Task`1 response)
   at Totoro.Plugins.Anime.AnimePahe.AiredEpisodesProvider.GetRecentlyAiredEpisodes(Int32 page)+MoveNext()
   at Totoro.Plugins.Anime.AnimePahe.AiredEpisodesProvider.GetRecentlyAiredEpisodes(Int32 page)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
```

4. Aniwave:
```
Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): GET https://9anime.eltik.net/vrf?query=eminence&apikey=saikou
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveString(Task`1 response)
   at Totoro.Plugins.Anime.Aniwave.Vrf.Encode(String text)
   at Totoro.Plugins.Anime.Aniwave.Catalog.Search(String query)+MoveNext()
   at Totoro.Plugins.Anime.Aniwave.Catalog.Search(String query)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
```

5. Gogo:
```
Flurl.Http.FlurlHttpException: Call failed. No such host is known. (gogoanimehd.io:443): GET https://gogoanimehd.io/search.html?keyword=eminenv
 ---> System.Net.Http.HttpRequestException: No such host is known. (gogoanimehd.io:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveStream(Task`1 response)
   at Totoro.Plugins.Helpers.FlurlExtensions.GetHtmlDocumentAsync(Url url) in D:\a\Totoro\Totoro\Totoro.Plugins\Helpers\FlurlExtensions.cs:line 38
   at Totoro.Plugins.Anime.GogoAnime.Catalog.Search(String query)+MoveNext()
   at Totoro.Plugins.Anime.GogoAnime.Catalog.Search(String query)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
```

**Comment by bachig26** [comment]
also since the player opens for yugen, it also does crashes the app #74 after few seconds of staying idle.

**Comment by insomniachi** [comment]
- for gogo anime change URL to "https://anitaku.to/"
they regularly change url, you can find the trust one in https://theindex.moe/collection/self-hosted-streaming-sites

- marin does not exist anymore

- aniwave is permanently broken
![image](https://github.com/insomniachi/Totoro/assets/6525704/276b0bbe-3474-4524-9b47-e48c428d6839)

rest i need to check

**Comment by insomniachi** [comment]
made a small fix for allanime, check if that works for you

**Comment by insomniachi** [comment]
> > made a small fix for allanime, check if that works for you
> 
> Anime pahe?

anime pahe is fixed
