### ISSUE TITLE
Crashing after choosing an episode and can't access to the My List tab

### ISSUE THREAD

**Issue by taekungzaza1111** [insomniachi/Totoro#85]
The crash after choosing an episode doesn't have any error it just disappeared.

This is the error code from My List tab

Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 288
--- End of stack trace from previous location ---
   at Totoro.Core.Services.Simkl.SimklService.GetId(ListServiceType type, Int64 id) in D:\a\Totoro\Totoro\Totoro.Core\Services\Simkl\SimklService.cs:line 19
   at Totoro.Core.Services.AnimeIdService.GetId(ListServiceType from, ListServiceType to, Int64 id) in D:\a\Totoro\Totoro\Totoro.Core\Services\AnimeIdService.cs:line 17
   at Totoro.Core.Services.AniList.AnilistService.GetNextAiringEpisode(Int64 id) in D:\a\Totoro\Totoro\Totoro.Core\Services\AniList\AniListService.cs:line 134
   at Totoro.Core.Services.MyAnimeList.MyAnimeListTrackingService.<GetAnime>b__9_0(IObserver`1 observer) in D:\a\Totoro\Totoro\Totoro.Core\Services\MyAnimeList\MyAnimeListTrackingService.cs:line 95
   
   *Edit*
   i've tried clean install and it kinda work for a day or two then the problem came back again 
   *2nd Edit* 
   nope it doesn't work now with clean install

**Comment by insomniachi** [comment]
fixed
