### ISSUE TITLE
Animelist

### ISSUE THREAD

**Issue by CapnCranch** [insomniachi/Totoro#94]
**Describe the bug**
When trying to refresh myanimelist it sends an error

**To Reproduce**
1. Go to 'My List'
2. Click on 'Refresh'
3. See error

**Expected behavior**
Show my full anime list from my animelist

**Screenshots**

**Desktop (please complete the following information):**
 - Version 1.61

**Additional context**

System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $.data[2].node.my_list_status.start_date | LineNumber: 0 | BytePositionInLine: 5168.
 ---> System.FormatException: The JSON value is not in a supported DateTime format.
   at System.Text.Json.ThrowHelper.ThrowFormatException(DataType dataType)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at MalApi.EndPoints.AnimeEndPoint.Parse[T](String url)
   at MalApi.EndPoints.AnimeEndPoint.ParsePagedAnime(String url)
   at MalApi.EndPoints.AnimeEndPoint.MalApi.Interfaces.IUserAnimeListRequest.Find()
   at Totoro.Core.Services.MyAnimeList.MyAnimeListTrackingService.GetAnime()+MoveNext() in E:\source\GitHub\Totoro\Totoro.Core\Services\MyAnimeList\MyAnimeListTrackingService.cs:line 77
   at Totoro.Core.Services.MyAnimeList.MyAnimeListTrackingService.GetAnime()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50

**Comment by ostinado** [comment]
I get this error myself all the time, ever since I started to use it.

**Comment by insomniachi** [comment]
looks like it cannot parse Start date in one of your anime in your list to a valid DateTime, i'll need any of your mal id to check which one that is, as i cannot reproduce it on my account.
@ostinado @CapnCranch

**Comment by ostinado** [comment]
Hey brother. I can message you the ID I think. But considering that this bug is randomly based on one of the thousands of titles available on the site, would there a way to disable that specific check, to have a workaround for when it happens again? 
I have no idea how difficult this would be, its just something that occurred to me. Thank you for addressing it.

**Comment by robert-desable** [comment]
Also encountered this error with MAL tracking. Could it be because of list entries with incomplete date (only month/year or only year) ?

**Comment by insomniachi** [comment]
that could cause this

**Comment by robert-desable** [comment]
> that could cause this

So I did remove all incomplete dates from my list, and now it works. That did cause this.
